Rename pkgname to pkgalias

diff --git a/bin/upkg b/bin/upkg
--- a/bin/upkg
+++ b/bin/upkg
@@ -127,13 +127,13 @@ upkg_add() {
 
 # Remove a package from upkg.json and run upkg_install
 upkg_remove() {
-  local pkgname=$1 pkgurl
-  pkgurl=$(upkg_get_pkg_url . "$pkgname")
+  local pkgalias=$1 pkgurl
+  pkgurl=$(upkg_get_pkg_url . "$pkgalias")
   # Modify upkg.json, but only in the temp dir, so a failure doesn't change anything
   jq -r --arg pkgurl "$pkgurl" 'del(.dependencies[$pkgurl])' upkg.json >.upkg/.tmp/root/upkg.json
   upkg_install
   [[ ! -e .upkg ]] || cp .upkg/.tmp/root/upkg.json upkg.json
-  processing "Removed '%s'" "$pkgname"
+  processing "Removed '%s'" "$pkgalias"
 }
 
 # List all top-level installed packages. Not based on upkg.json, but the actually installed packages
@@ -142,15 +142,15 @@ upkg_list() {
     if [[ ! -e .upkg ]]; then
       processing "No packages are installed in '%s'" "$PWD"
     fi
-    local dedup_pkgpath basename pkgname checksum version upkgjsonpath version
+    local dedup_pkgpath basename pkgalias checksum version upkgjsonpath version
     while read -r -d $'\n' dedup_pkgpath; do
       basename=$(basename "$dedup_pkgpath")
-      pkgname=${basename%@*}
+      pkgalias=${basename%@*}
       checksum=${basename#*@}
       version='no-version'
       upkgjsonpath=.upkg/$dedup_pkgpath/upkg.json
       [[ ! -e "$upkgjsonpath" ]] || version=$(jq -r '.version // "no-version"' "$upkgjsonpath")
-      printf "%s\t%s\t%s\n" "$pkgname" "$version" "$checksum"
+      printf "%s\t%s\t%s\n" "$pkgalias" "$version" "$checksum"
     done < <(find .upkg -mindepth 1 -maxdepth 1 -not -name '.*' -exec readlink \{\} \;) # Don't descend into .packages, we only want the top-level
   ) | (
     # Allow nice formatting if `column` (from bsdextrautils) is installed
@@ -184,7 +184,7 @@ upkg_install() {
 
   # Copy new packages and all symlinks from .upkg/.tmp
   if ! $DRY_RUN; then
-    # .bin/ and all pkgname symlinks are fully rebuilt during install, so we just remove it and copy it over
+    # .bin/ and all pkgalias symlinks are fully rebuilt during install, so we just remove it and copy it over
     rm -rf .upkg/.bin
     rm -f .upkg/*
     if [[ -e .upkg/.tmp/root/.upkg ]]; then
@@ -231,16 +231,16 @@ upkg_install() {
 
 # Get the URL of a package via its package name
 upkg_get_pkg_url() {
-  local pkgpath=$1 pkgname=$2 checksum
-  [[ -e "$pkgpath/.upkg/$pkgname" ]] || fatal "Unable to find '%s' in '%s'" "$pkgname" "$pkgpath/.upkg"
+  local pkgpath=$1 pkgalias=$2 checksum
+  [[ -e "$pkgpath/.upkg/$pkgalias" ]] || fatal "Unable to find '%s' in '%s'" "$pkgalias" "$pkgpath/.upkg"
   # Use the .upkg/pkg symlink to get the .package path ...
-  checksum=$(readlink "$pkgpath/.upkg/$pkgname")
+  checksum=$(readlink "$pkgpath/.upkg/$pkgalias")
   checksum=$(basename "$checksum")
   # ... extract the checksum from that name ...
   checksum=${checksum#*@}
   # ... and then look it up in upkg.json
   if ! jq -re --arg checksum "$checksum" '.dependencies | to_entries[] | select(.value==$checksum) | .key // empty' "$pkgpath/upkg.json"; then
-    fatal "'%s' is not listed in '%s'" "$pkgname" "$pkgpath/upkg.json"
+    fatal "'%s' is not listed in '%s'" "$pkgalias" "$pkgpath/upkg.json"
   fi
 }
 
@@ -330,7 +330,7 @@ upkg_install_deps() {
 
 # Obtain (copy, download, clone, extract.. whatever) a package, symlink its commands and the install its dependencies
 upkg_install_pkg() {
-  local pkgurl=$1 checksum=$2 parentpath=$3 dedupname pkgname is_dedup=false
+  local pkgurl=$1 checksum=$2 parentpath=$3 dedupname pkgalias is_dedup=false
   # Acquire a shared lock which is released once this process completes. Fail if we can't lock
   exec 9<>"$parentpath/upkg.json"; flock -ns 9
   touch "$parentpath/.upkg/.sentinels/$checksum.lock" # Tell the parent process that the shared lock has been acquired
@@ -348,21 +348,21 @@ upkg_install_pkg() {
     dedupname=$(upkg_download "$pkgurl" "$checksum")
   fi
 
-  pkgname=$dedupname
-  if [[ $pkgurl =~ \#name=([^#]+)(\#|$) ]]; then
+  pkgalias=$dedupname
+  if [[ $pkgurl =~ \#alias=([^#]+)(\#|$) ]]; then
     # Package name override specified
-    pkgname=${BASH_REMATCH[1]}
+    pkgalias=${BASH_REMATCH[1]}
   fi
-  [[ $pkgname =~ ^[@/]+$ || $pkgname != .* ]] ||
+  [[ $pkgalias =~ ^[@/]+$ || $pkgalias != .* ]] ||
     fatal "The package from '%s' has an invalid package name or name override \
-('@/' are disallowed, may not be empty or start with '.'): '%s'" "$pkgurl" "$pkgname"
+('@/' are disallowed, may not be empty or start with '.'): '%s'" "$pkgurl" "$pkgalias"
 
   # Atomic operation, if this fails there is a duplicate
-  if ! ln -s ".packages/$dedupname@$checksum" "$parentpath/.upkg/$pkgname"; then
+  if ! ln -s ".packages/$dedupname@$checksum" "$parentpath/.upkg/$pkgalias"; then
     # TODO: Generate dependency tree from pkgpath
-    fatal "conflict: There is more than one package with the name '%s'" "$pkgname"
+    fatal "conflict: There is more than one package with the name '%s'" "$pkgalias"
   fi
-  local pkgpath="$parentpath/.upkg/$pkgname" command cmdpath otherpkg
+  local pkgpath="$parentpath/.upkg/$pkgalias" command cmdpath otherpkg
   if [[ -e "$pkgpath/bin" ]]; then
     # package has a bin/ dir, symlink the executable files in that directory
     mkdir -p "$parentpath/.upkg/.bin"
@@ -370,23 +370,23 @@ upkg_install_pkg() {
       command=$(basename "$command")
       cmdpath="$parentpath/.upkg/.bin/$command"
       # Atomic operation, if this fails there is a duplicate
-      if ! ln -s "../$pkgname/bin/$command" "$cmdpath" 2>/dev/null; then
+      if ! ln -s "../$pkgalias/bin/$command" "$cmdpath" 2>/dev/null; then
         otherpkg=$(readlink "$cmdpath")
         otherpkg=${otherpkg#'../'}
         otherpkg=${otherpkg%%'/'*}
-        fatal "conflict: '%s' and '%s' both have a command named '%s'" "$pkgname" "$otherpkg" "$command"
+        fatal "conflict: '%s' and '%s' both have a command named '%s'" "$pkgalias" "$otherpkg" "$command"
       fi
     done < <(find "$pkgpath/bin" -mindepth 1 -maxdepth 1 -type f -executable)
   elif [[ $pkgurl =~ \#bin(\#|$) ]]; then
     # pkgurl is a file (and has been validated as such in upkg_download), symlink from bin
     mkdir -p "$parentpath/.upkg/.bin"
-    cmdpath="$parentpath/.upkg/.bin/$pkgname"
+    cmdpath="$parentpath/.upkg/.bin/$pkgalias"
     # Atomic operation, if this fails there is a duplicate
-    if ! ln -s "../$pkgname" "$cmdpath" 2>/dev/null; then
+    if ! ln -s "../$pkgalias" "$cmdpath" 2>/dev/null; then
       otherpkg=$(readlink "$cmdpath")
       otherpkg=${otherpkg#'../'}
       otherpkg=${otherpkg%%'/'*}
-      fatal "conflict: '%s' and '%s' both have a command named '%s'" "$pkgname" "$otherpkg" "$pkgname"
+      fatal "conflict: '%s' and '%s' both have a command named '%s'" "$pkgalias" "$otherpkg" "$pkgalias"
     fi
   fi
 
@@ -394,7 +394,7 @@ upkg_install_pkg() {
   $is_dedup || upkg_install_deps "$pkgpath"
 }
 
-# Copy, download, clone a package, check the checksum, maybe set a version, maybe calculate a pkgname, return the pkgname
+# Copy, download, clone a package, check the checksum, maybe set a version, maybe calculate a package name, return the package name
 upkg_download() (
   local pkgurl=$1 checksum=$2 dedupname
   mkdir -p .upkg/.tmp/download
@@ -527,7 +527,7 @@ validate_pkgurl() {
     fatal "'%s' has been marked with #bin to be an executable, but the URL points at a tar archive" "$pkgurl"
   [[ $urltype != git || ! $pkgurl =~ \#bin(\#|$) ]] || \
     fatal "'%s' has been marked with #bin to be an executable, but the URL points at a git repository" "$pkgurl"
-  [[ $pkgurl =~ (\#name=([^.][^#@/]+)(\#|$))? ]] || \
+  [[ $pkgurl =~ (\#alias=([^.][^#@/]+)(\#|$))? ]] || \
     fatal "The package URL '%s' specifies an invalid package name override (contains @ or /, is empty or starts with '.')'" "$pkgurl"
 }
 
