Enable inherit errexit

diff --git a/bin/upkg b/bin/upkg
--- a/bin/upkg
+++ b/bin/upkg
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 # shellcheck disable=2059,2064
 set -Eeo pipefail
+shopt -s inherit_errexit
 
 upkg() {
   [[ ! $(bash --version | head -n1) =~ version\ [34]\.[0-3] ]] || fatal "upkg requires bash >= v4.4"
@@ -537,7 +538,7 @@ upkg_mktemp() {
   mkdir .upkg/.tmp || fatal "Another upkg instance is already installing to '%s'" "$PWD" # Implicit lock
   mkdir .upkg/.tmp/root # Precreate root dir, we always need it
   if ! ${UPKG_KEEP_TMP:-false}; then
-    # Cleanup when done, make sure no subshell ever calls these traps
+    # Cleanup when done, make sure no subshell ever calls these traps (set -E is on)
     trap "[[ \$BASHPID != $BASHPID ]] || rm -rf .upkg/.tmp" EXIT
     $keep_dotupkg || trap "[[ \$BASHPID != $BASHPID ]] || rm -rf .upkg" ERR
   fi
