bundle: Actually fail when package has no name and no --dest was provided

diff --git a/bin/upkg b/bin/upkg
--- a/bin/upkg
+++ b/bin/upkg
@@ -216,7 +216,7 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
       [[ $asset_path != .upkg && $asset_path != .upkg/* ]] || fatal ".upkg may not be included in the package"
     done
     if [[ -z $___dest ]]; then
-      ___dest=$(jq -r .name upkg.json).tar.gz || fatal "Unable to determine package name"
+      ___dest=$(jq -re '.name // empty' upkg.json).tar.gz || fatal "Unable to determine package name"
     fi
     upkg_mktemp
     upkg_bundle "$___pkgver" "$___dest" "${_PATHS[@]}"
