Add `bundle` command, allowing bundling directly using μpkg

diff --git a/bin/upkg b/bin/upkg
--- a/bin/upkg
+++ b/bin/upkg
@@ -30,57 +30,66 @@ Usage:
   upkg add [-qvgXB -b PATH... -p PKGNAME -t PKGTYPE] (URL|PATH) [SHA]
   upkg remove [-qnvg] PKGNAME
   upkg list [-qvg] [-- COLUMNOPTS...]
+  upkg bundle [-qv -d PATH] -V VERSION [PATHS...]
 
 Options:
-  -n --dry-run       Dry run, \$?=1 if install is required
-  -q --quiet         Log only fatal errors
-  -v --verbose       Output verbose logs and disable writing to the same line
-  -g --global        Act globally
-  -X --no-exec       Do not chmod +x the file (implies --no-bin)
-  -B --no-bin        Do not link executables in package bin/ to .upkg/.bin
-  -b --bin=PATH      Link specified executables or contents of specified
-                     directory to .upkg/.bin (default: bin/)
-  -t --pkgtype=TYPE  Explicitly set the package type (tar, file, or git)
-  -p --pkgname=NAME  Override the package name link in .upkg/
+  -n --dry-run          Dry run, \$?=1 if install is required
+  -q --quiet            Log only fatal errors
+  -v --verbose          Output verbose logs and disable writing to the same line
+  -g --global           Act globally
+  -X --no-exec          Do not chmod +x the file (implies --no-bin)
+  -B --no-bin           Do not link executables in package bin/ to .upkg/.bin
+  -b --bin=PATH         Link specified executables or contents of specified
+                        directory to .upkg/.bin (default: bin/)
+  -t --pkgtype=TYPE     Explicitly set the package type (tar, file, or git)
+  -p --pkgname=NAME     Override the package name link in .upkg/
+  -d --dest=PATH        Package tarball destination (default: \$pkgname.tar.gz)
+  -V --version=VERSION  Version of the package that is being bundled
 "
 # shellcheck disable=SC2317
 # docopt parser below, refresh this parser with `docopt.sh upkg`
 # shellcheck disable=2016,2086,2317,1090,1091,2034,2154
 docopt() { source "$PKGROOT/.upkg/docopt-lib.sh/docopt-lib.sh" '2.0.0a3' || {
 ret=$?;printf -- "exit %d\n" "$ret";exit "$ret";};set -e
-trimmed_doc=${DOC:0:834};usage=${DOC:36:166};digest=32dd9;options=('-n --dry-r'\
-'un 0' '-q --quiet 0' '-v --verbose 0' '-g --global 0' '-X --no-exec 0' '-B --'\
-'no-bin 0' '-b --bin 1' '-p --pkgname 1' '-t --pkgtype 1');node_0(){ switch \
-__dry_run 0;};node_1(){ switch __quiet 1;};node_2(){ switch __verbose 2;}
-node_3(){ switch __global 3;};node_4(){ switch __no_exec 4;};node_5(){ switch \
-__no_bin 5;};node_6(){ value __bin 6 true;};node_7(){ value __pkgname 7;}
-node_8(){ value __pkgtype 8;};node_9(){ value URL a;};node_10(){ value PATH a;}
-node_11(){ value SHA a;};node_12(){ value PKGNAME a;};node_13(){ value \
-COLUMNOPTS a true;};node_14(){ switch install a:install;};node_15(){ switch \
-add a:add;};node_16(){ switch remove a:remove;};node_17(){ switch list a:list;}
-node_18(){ switch __ a:--;};node_19(){ sequence 14 20;};node_20(){ optional 0 \
-1 2;};node_21(){ sequence 15 22 24 25;};node_22(){ optional 1 2 3 4 5 23 7 8;}
-node_23(){ repeatable 6;};node_24(){ choice 9 10;};node_25(){ optional 11;}
-node_26(){ sequence 16 27 12;};node_27(){ optional 1 0 2 3;};node_28(){
-sequence 17 29 30;};node_29(){ optional 1 2 3;};node_30(){ optional 18 31;}
-node_31(){ repeatable 13;};node_32(){ choice 19 21 26 28;};cat <<<' \
-docopt_exit() { [[ -n $1 ]] && printf "%s\n" "$1" >&2;printf "%s\n" \
-"${DOC:36:166}" >&2;exit 1;}';local varnames=(__dry_run __quiet __verbose \
-__global __no_exec __no_bin __bin __pkgname __pkgtype URL PATH SHA PKGNAME \
-COLUMNOPTS install add remove list __) varname;for varname in \
-"${varnames[@]}"; do unset "var_$varname";done;parse 32 "$@";local \
-p=${DOCOPT_PREFIX:-''};for varname in "${varnames[@]}"; do unset "$p$varname"
-done;if declare -p var___bin >/dev/null 2>&1; then eval $p'__bin=("${var___bin'\
-'[@]}")';else eval $p'__bin=()';fi;if declare -p var_COLUMNOPTS >/dev/null \
-2>&1; then eval $p'COLUMNOPTS=("${var_COLUMNOPTS[@]}")';else eval $p'COLUMNOPT'\
-'S=()';fi;eval $p'__dry_run=${var___dry_run:-false};'$p'__quiet=${var___quiet:'\
-'-false};'$p'__verbose=${var___verbose:-false};'$p'__global=${var___global:-fa'\
-'lse};'$p'__no_exec=${var___no_exec:-false};'$p'__no_bin=${var___no_bin:-false'\
-'};'$p'__pkgname=${var___pkgname:-};'$p'__pkgtype=${var___pkgtype:-};'$p'URL=$'\
-'{var_URL:-};'$p'PATH=${var_PATH:-};'$p'SHA=${var_SHA:-};'$p'PKGNAME=${var_PKG'\
-'NAME:-};'$p'install=${var_install:-false};'$p'add=${var_add:-false};'$p'remov'\
-'e=${var_remove:-false};'$p'list=${var_list:-false};'$p'__=${var___:-false};'
-local docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
+trimmed_doc=${DOC:0:1062};usage=${DOC:36:216};digest=7b01d;options=('-n --dry-'\
+'run 0' '-q --quiet 0' '-v --verbose 0' '-g --global 0' '-X --no-exec 0' '-B -'\
+'-no-bin 0' '-b --bin 1' '-p --pkgname 1' '-t --pkgtype 1' '-d --dest 1' '-V -'\
+'-version 1');node_0(){ switch __dry_run 0;};node_1(){ switch __quiet 1;}
+node_2(){ switch __verbose 2;};node_3(){ switch __global 3;};node_4(){ switch \
+__no_exec 4;};node_5(){ switch __no_bin 5;};node_6(){ value __bin 6 true;}
+node_7(){ value __pkgname 7;};node_8(){ value __pkgtype 8;};node_9(){ value \
+__dest 9;};node_10(){ value __version 10;};node_11(){ value URL a;};node_12(){
+value PATH a;};node_13(){ value SHA a;};node_14(){ value PKGNAME a;};node_15(){
+value COLUMNOPTS a true;};node_16(){ value PATHS a true;};node_17(){ switch \
+install a:install;};node_18(){ switch add a:add;};node_19(){ switch remove \
+a:remove;};node_20(){ switch list a:list;};node_21(){ switch bundle a:bundle;}
+node_22(){ switch __ a:--;};node_23(){ sequence 17 24;};node_24(){ optional 0 \
+1 2;};node_25(){ sequence 18 26 28 29;};node_26(){ optional 1 2 3 4 5 27 7 8;}
+node_27(){ repeatable 6;};node_28(){ choice 11 12;};node_29(){ optional 13;}
+node_30(){ sequence 19 31 14;};node_31(){ optional 1 0 2 3;};node_32(){
+sequence 20 33 34;};node_33(){ optional 1 2 3;};node_34(){ optional 22 35;}
+node_35(){ repeatable 15;};node_36(){ sequence 21 37 10 38;};node_37(){
+optional 1 2 9;};node_38(){ optional 39;};node_39(){ repeatable 16;};node_40(){
+choice 23 25 30 32 36;};cat <<<' docopt_exit() { [[ -n $1 ]] && printf "%s\n" \
+"$1" >&2;printf "%s\n" "${DOC:36:216}" >&2;exit 1;}';local varnames=(__dry_run \
+__quiet __verbose __global __no_exec __no_bin __bin __pkgname __pkgtype __dest \
+__version URL PATH SHA PKGNAME COLUMNOPTS PATHS install add remove list bundle \
+__) varname;for varname in "${varnames[@]}"; do unset "var_$varname";done
+parse 40 "$@";local p=${DOCOPT_PREFIX:-''};for varname in "${varnames[@]}"; do
+unset "$p$varname";done;if declare -p var___bin >/dev/null 2>&1; then eval \
+$p'__bin=("${var___bin[@]}")';else eval $p'__bin=()';fi;if declare -p \
+var_COLUMNOPTS >/dev/null 2>&1; then eval $p'COLUMNOPTS=("${var_COLUMNOPTS[@]}'\
+'")';else eval $p'COLUMNOPTS=()';fi;if declare -p var_PATHS >/dev/null 2>&1; \
+then eval $p'PATHS=("${var_PATHS[@]}")';else eval $p'PATHS=()';fi;eval $p'__dr'\
+'y_run=${var___dry_run:-false};'$p'__quiet=${var___quiet:-false};'$p'__verbose'\
+'=${var___verbose:-false};'$p'__global=${var___global:-false};'$p'__no_exec=${'\
+'var___no_exec:-false};'$p'__no_bin=${var___no_bin:-false};'$p'__pkgname=${var'\
+'___pkgname:-};'$p'__pkgtype=${var___pkgtype:-};'$p'__dest=${var___dest:-};'\
+$p'__version=${var___version:-};'$p'URL=${var_URL:-};'$p'PATH=${var_PATH:-};'\
+$p'SHA=${var_SHA:-};'$p'PKGNAME=${var_PKGNAME:-};'$p'install=${var_install:-fa'\
+'lse};'$p'add=${var_add:-false};'$p'remove=${var_remove:-false};'$p'list=${var'\
+'_list:-false};'$p'bundle=${var_bundle:-false};'$p'__=${var___:-false};';local \
+docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
 ((;docopt_i>0;docopt_i--)); do for varname in "${varnames[@]}"; do declare -p \
 "$p$varname";done;done;}
 # docopt parser above, complete command for generating this parser is `docopt.sh --library='"$PKGROOT/.upkg/docopt-lib.sh/docopt-lib.sh"' upkg`
@@ -95,6 +104,7 @@ local docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
   source "$PKGROOT/lib/install.sh"
   source "$PKGROOT/lib/remove.sh"
   source "$PKGROOT/lib/add.sh"
+  source "$PKGROOT/lib/bundle.sh"
 
   # Make sure we have jq available, git and tar are optional and we let them fail once we get there
   type "jq" >/dev/null 2>&1 || fatal "command not found: 'jq'"
@@ -196,6 +206,20 @@ local docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
       cd "$INSTALL_PREFIX/lib/upkg"
     fi
     upkg_list "${COLUMNOPTS[@]}"
+
+  elif $_bundle; then
+    [[ -e "$PWD/upkg.json" ]] || fatal "No upkg.json found in '%s'" "$PWD"
+    local asset_path
+    for asset_path in "${_PATHS[@]}"; do
+      [[ $asset_path != upkg.json ]] || fatal "You must not specify upkg.json in PATHS"
+      [[ $asset_path != .upkg && $asset_path != .upkg/* ]] || fatal ".upkg may not be included in the package"
+    done
+    if [[ -z $___dest ]]; then
+      ___dest=$(jq -r .name upkg.json).tar.gz || fatal "Unable to determine package name"
+    fi
+    upkg_mktemp
+    upkg_bundle "$___version" "$___dest" "${_PATHS[@]}"
+    completed "μpkg package tarball was successfully created at '%s'" "$___dest"
 
   else
     fatal "Not implemented"
